### ISSUE TITLE
(cf-sbd-server) integrate into sbd-o-bahn and write additional server tests

### ISSUE THREAD

**Issue by neonphog** [holochain/sbd#28]
DEPENDS ON https://github.com/holochain/sbd/issues/27

sbd-o-bahn is a testing framework akin to the websocket autobahn suite. Currently it just has a single sanity test and runs against the rust sbd server.

Now that we also have a cloudflare sbd server:
- set up a test runner that can spawn the wrangler-dev/miniflare cloudflare sbd server
- ensure it passes the sanity test
- write more tests to effect a decent coverage of the server functionality (making sure the rust server passes as well)

**Comment by abe-njama** [comment]
@neonphog what specs would be ideal for the SBD server on Cloudflare?
cc @evangineer
